.PHONY: build-MatchingFunction
build-MatchingFunction:
	python -m pip install -r requirements.txt --target "$(ARTIFACTS_DIR)"
	mkdir -p "$(ARTIFACTS_DIR)/matching"
	cp *.py "$(ARTIFACTS_DIR)/matching/"
