CREATE TYPE "professional_status" AS ENUM (
  'register_pending',
  'under_review',
  'approved',
  'rejected',
  'payment_pending',
  'active',
  'inactive'
);

CREATE TYPE "channel" AS ENUM (
  'telegram',
  'whatsapp'
);

CREATE TABLE IF NOT EXISTS "person" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone_number" varchar UNIQUE NOT NULL,
  "name" varchar,
  "cpf" varchar UNIQUE,
  "channel" channel,
  "created_at" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "professional" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int UNIQUE NOT NULL,
  "area" varchar NOT NULL,
  "professional_register" varchar NOT NULL,
  "register_type" varchar NOT NULL,
  "approach" text,
  "background" text,
  "video_platform" varchar,
  "email" varchar,
  "status_id" int UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "patient" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int UNIQUE NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "professional_patient" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "professional_id" int NOT NULL,
  "patient_id" int NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS "message_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" int NOT NULL,
  "created_at" timestamp NOT NULL,
  "content" text,
  "image_url" text,
  "document_url" text,
  "is_from_user" boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS "professional_status_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "professional_id" int NOT NULL,
  "professional_status" professional_status NOT NULL,
  "created_at" timestamp NOT NULL
);

ALTER TABLE "professional"
  ADD FOREIGN KEY ("person_id")
  REFERENCES "person" ("id")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "professional"
  ADD FOREIGN KEY ("status_id")
  REFERENCES "professional_status_history" ("id")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "patient"
  ADD FOREIGN KEY ("person_id")
  REFERENCES "person" ("id")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "professional_patient"
  ADD FOREIGN KEY ("professional_id")
  REFERENCES "professional" ("id")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "professional_patient"
  ADD FOREIGN KEY ("patient_id")
  REFERENCES "patient" ("id")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "message_history"
  ADD FOREIGN KEY ("person_id")
  REFERENCES "person" ("id")
  DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "professional_status_history"
  ADD FOREIGN KEY ("professional_id")
  REFERENCES "professional" ("id")
  DEFERRABLE INITIALLY IMMEDIATE;