name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: []

    steps:
      - uses: actions/checkout@v4

      - name: Copy code to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: ${{ secrets.EC2_APP_PATH }}
          rm: false
          strip_components: 0
          overwrite: true

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_APP_PATH }}

            # Se o container da API estiver rodando, apenas subsititui ela.
            # Caso não, subsititui tudo;
            if docker compose ps --services --filter status=running | grep -q "^chatbot$"; then
              echo "Stack already running, rebuilding chatbot service only"
              docker compose up -d --build chatbot
              
            else
              echo "Stack not running — starting full stack"
              docker compose up -d --build
            fi

            docker compose ps
            echo "Finished!"
