"""Telegram-specific bot adapters implementing the abstract bot contracts."""

import logging
import os

import telegram
from telegram.ext import (
    Application,
    ApplicationBuilder,
    CallbackQueryHandler,
    ContextTypes,
    MessageHandler,
    filters,
)

from app.domain.message import Message

from .bot import Bot, BotContext
from .bot import MessageHandler as BaseMessageHandler

logger = logging.getLogger(__name__)
TOKEN_ENV_VAR = "TELEGRAM_BOT_TOKEN"  # noqa: S105


class TelegramBotContext(BotContext):
    """Concrete context wrapper for Telegram updates and chat actions."""

    def __init__(self, update: telegram.Update, context: ContextTypes.DEFAULT_TYPE):
        """Initialize context from Telegram update and framework context."""
        self.update = update
        self.context = context
        self.chat_id = str(update.effective_chat.id) if update.effective_chat else None
        self.user_id = str(update.effective_user.id) if update.effective_user else None

    async def send_message(
        self, text: str, choices: dict[str, str] | None = None
    ) -> None:
        """Reply to the current Telegram message, optionally with inline choices."""
        if self.update.message:
            reply_markup = None
            if choices:
                keyboard = [
                    [telegram.InlineKeyboardButton(label, callback_data=key)]
                    for (key, label) in choices.items()
                ]
                reply_markup = telegram.InlineKeyboardMarkup(keyboard)

            await self.update.message.reply_text(text, reply_markup=reply_markup)
            logger.info("Response sent to User: %s", self.user_id)

    async def start_typing(self) -> None:
        """Send typing action to Telegram chat while processing a request."""
        if self.chat_id:
            await self.context.bot.send_chat_action(
                chat_id=self.chat_id, action="typing"
            )


class TelegramBot(Bot):
    """Telegram bot runtime that forwards events to a message handler."""

    token: str
    handler: BaseMessageHandler

    def __init__(self, message_handler: BaseMessageHandler, token: str | None = None):
        """Initialize bot credentials and handler callbacks."""
        t = token or os.getenv(TOKEN_ENV_VAR)

        if not t:
            logger.error("%s not found in environment variables", TOKEN_ENV_VAR)
            raise ValueError(
                f"Error: {TOKEN_ENV_VAR} is not set in the environment variables."
            )
        self.token = t
        self.handler = message_handler

    async def on_message(
        self, update: telegram.Update, context: ContextTypes.DEFAULT_TYPE
    ) -> None:
        """Handle inbound Telegram text messages and delegate processing."""
        if not update.effective_chat:
            logger.warning("Update received without effective_chat")
            return

        if not update.message or not update.message.text:
            logger.warning("Update received without message text")
            return

        user_id = update.effective_user.id if update.effective_user else "unknown"
        chat_id = update.effective_chat.id
        message_text = update.message.text

        logger.info("Message received - User: %s, Chat: %s", user_id, chat_id)
        logger.debug("Message text: %s", message_text)

        message = Message(
            chat_id=str(chat_id),
            user_id=str(user_id),
            content=message_text,
            origin="telegram",
        )

        bot_context = TelegramBotContext(update, context)

        await self.handler.on_message(bot_context, message)

    async def on_callback_query(
        self, update: telegram.Update, context: ContextTypes.DEFAULT_TYPE
    ) -> None:
        """Handle Telegram callback queries generated by inline keyboards."""
        query = update.callback_query
        if query:
            await query.answer()
            logger.info("Callback query received: %s", query.data)

            if query.data is None:
                logger.warning("Callback query received without data")
                return

            await self.handler.on_option_selected(
                query.data, TelegramBotContext(update, context)
            )
            # Handle callback query as needed

    def __setup_application(self) -> Application:  # type: ignore[type-arg]
        """Create Telegram application and register message/query handlers."""
        logger.info("Setting up Telegram application...")
        app = ApplicationBuilder().token(self.token).build()
        app.add_handler(
            MessageHandler(filters.TEXT & ~filters.COMMAND, self.on_message)
        )
        app.add_handler(CallbackQueryHandler(self.on_callback_query))
        return app

    async def run(self) -> None:
        """Start the Telegram polling loop."""
        logger.info("Setting up Telegram application...")
        app = self.__setup_application()

        logger.info("Bot started and waiting for messages...")
        await app.start()
